language: python
python:
  - "3.8"
  - "3.9"

# Define environment variables
env:
  global:
    - MARTIAN_ENVIRONMENT=true

# Install dependencies
install:
  - pip install -r requirements.txt

# Run tests
script:
  - pytest

# Simulate Martian deployment
deploy:
  provider: script
  script: bash deploy_to_mars.sh
  on:
    branch: main
