version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/project

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt

      # Run tests
      - run:
          name: Run tests
          command: |
            pytest

      # Simulate Martian deployment
      - run:
          name: Deploy to Mars
          command: |
            bash deploy_to_mars.sh
